"""init

Revision ID: 2a76813b1f29
Revises: 
Create Date: 2019-11-24 16:03:11.073433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a76813b1f29'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listeners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_listeners')),
    sa.UniqueConstraint('uuid', name=op.f('uq_listeners_uuid'))
    )
    op.create_table('active_listeners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('listener_ip', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], name=op.f('fk_active_listeners_listener_id_listeners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_active_listeners'))
    )
    op.create_table('icecast_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listener_id', sa.Integer(), nullable=True),
    sa.Column('max_listeners', sa.Integer(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['listener_id'], ['listeners.id'], name=op.f('fk_icecast_access_listener_id_listeners')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_icecast_access'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('icecast_access')
    op.drop_table('active_listeners')
    op.drop_table('listeners')
    # ### end Alembic commands ###
