"""test02

Revision ID: 49170dae556f
Revises: 6e5df391d0de
Create Date: 2019-11-23 22:53:52.561734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49170dae556f'
down_revision = '6e5df391d0de'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exp_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.drop_index('test_index', table_name='test_table')
    op.drop_table('test_table')
    op.drop_index('test2_index', table_name='test_table2')
    op.drop_table('test_table2')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_table2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_test_table2')
    )
    op.create_index('test2_index', 'test_table2', ['name'], unique=1)
    op.create_table('test_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=True),
    sa.Column('value', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_test_table')
    )
    op.create_index('test_index', 'test_table', ['name'], unique=1)
    op.drop_table('users')
    op.drop_table('access')
    # ### end Alembic commands ###
